function alpha = getAlphabet(source,type,varargin)
	%================================================================================================
    % Name:  getAlphabet
    %
    % Input arguments :
    %                    #  source-> Symbol source (matrix of a certain type)
    %                    #  type -> The type of the source matrix
    %                                      	   >>> TYPE TABLE <<<
    %                         »» text ==> source obtained from ".txt" file (char matrix)
    %                         »» image ==> source obtained from ".bmp" file (uint8 matrix) 
    %                         »» audio ==> source obtained from ".txt" file (double matrix)
    %                    # varagin (file) 
    %                           -> The Symbol source file in case we need to obtain more 
    %                                 information like in the case of the audio file
    %
    % Description :
    % This function builds an alphabet with the unique symbols from a given source
    % Its ready to obtain alphabets from sources specified by the type argument
    %
    % Output:
    %                    # alpha -> The alphabet generated by analysis of the source
    %================================================================================================

    if(type == "audio" && nargin == 3)
        info = audioinfo(string(varargin(1)));
        d = 2 / pow2(info.BitsPerSample);  % Formula ->  (1 -  (-1)) / 2^BitsPerSample
        alpha = -1 : d : (1- d);
    elseif (type == "text")
        alpha = unique(source);
        alpha = alpha( alpha <= 'Z' & alpha >='A' | alpha <= 'z' & alpha >= 'a'| alpha <= '9' & alpha >= '0' );
    else
        alpha = unique(source);
    end
 
end